function productionRateSym = productionRateFunction(ss3,ss4,ss5,ss9,ss10,ss11,ss15,ss16,ss17)
%PRODUCTIONRATEFUNCTION
%    PRODUCTIONRATESYM = PRODUCTIONRATEFUNCTION(SS3,SS4,SS5,SS9,SS10,SS11,SS15,SS16,SS17)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Apr-2021 15:26:03

productionRateSym = ss3+ss4+ss5+ss9+ss10+ss11+ss15+ss16+ss17;
